### ISSUE TITLE
Throax has the wrong image on shipyard tool bar

### ISSUE THREAD

**Issue by FootyMD** [JCharante/Sins-of-a-New-Eden-Empire#3]

**Comment by kabivel** [comment]
There isnt a thorax, you mean deimos or phobos ?

**Comment by FootyMD** [comment]
Well its thorax in research and has two upgrades, deimos and phobos

Ship yard as phobos twice

**Comment by kabivel** [comment]
Cant find the erro you talked about, can you put some print screen to facilitate ?

		Page:0
			count 9
			entityDefName "Gallente_Ship_Frigate_Imicus"
			entityDefName "Gallente_Ship_Frigate_Incursus"
			entityDefName "Gallente_Ship_Frigate_Atron"
			entityDefName "Gallente_Ship_Frigate_Tristan"
			entityDefName "Gallente_Ship_Destroyer_Catalyst"
			entityDefName "Gallente_Ship_Cruiser_Vexor"
			entityDefName "Gallente_Ship_Cruiser_Celestis"
			entityDefName "Gallente_Ship_Cruiser_Execuror"
			entityDefName "Gallente_Ship_Colony_Orca"
		Page:1
			count 9
			entityDefName "Gallente_Ship_Battlecruiser_Brutix"
			entityDefName "Gallente_Ship_Battlecruiser_Myrmidon"
			entityDefName "Gallente_Ship_Cruiser_Phobos"
			entityDefName "Gallente_Ship_Battleship_Dominix"
			entityDefName "Gallente_Ship_Battleship_Megathron"
			entityDefName "Gallente_Ship_Battleship_Hyperion"
			entityDefName "Gallente_Ship_Envoy_Brutix"
			entityDefName "Gallente_Ship_Battleship_Vindicator"
			entityDefName "Gallente_Ship_Destroyer_Hecate"

**Comment by kabivel** [comment]
[Phobos.zip](https://github.com/JCharante/Sins-of-a-New-Eden-Empire/files/861215/Phobos.zip)
Phobos Fix
Type: Update
Change to manifest: No
Folders affected: Window
