### ISSUE TITLE
Ragnarok has the incorrect name in the capital ships yard icon

### ISSUE THREAD

**Issue by FootyMD** [JCharante/Sins-of-a-New-Eden-Empire#4]

**Comment by kabivel** [comment]
Fix: Replace this lines on Minmatar_Ship_Capital_Titan_Ragnarok and in Minmatar_Ship_Titan_Ragnarok

NameStringID "IDS_TITAN_MINMATAR_NAME"
DescriptionStringID "IDS_TITAN_MINMATAR_DESCRIPTION"

**Comment by FootyMD** [comment]
Fixed
