### ISSUE TITLE
sansha balance, too powerful early game

### ISSUE THREAD

**Issue by Gimlie102** [JCharante/Sins-of-a-New-Eden-Empire#41]
sanshas seem a bit overpowered, on the receiving end of an incursion around 15 minutes into the game almost a dozen sansha frigs arrived at my homeworld. 

seems like either reducing amount of sansha spawn or rebalancing individual sansha ships might need to be done, as currently each frig has 30-60% damage resists and 1000+ shield HP, not to mention neuting power

**Comment by FootyMD** [comment]
Will look into changing either the spawn rate or the hp

**Comment by teroni** [comment]
The uroborus also has entirely way too much HP, if it's going to be that much HP, the experience value should reflect it.

**Comment by FootyMD** [comment]
This will be updated in this coming patch on 24/04/2017

**Comment by JCharante** [comment]
Fixed in https://github.com/JCharante/Sins-of-a-New-Eden-Empire/commit/f373b5f233163cf3de9e2a5ae1fb5dec06531fda
