### ISSUE TITLE
Svipul has no icon in the minmatar research tree

### ISSUE THREAD

**Issue by FootyMD** [JCharante/Sins-of-a-New-Eden-Empire#5]

**Comment by kabivel** [comment]
Svipul position in the file is empty, files need to be edited:
Ships_Buttons_CursorOver
Ships_Buttons_Disabled
Ships_Buttons_Normal
Ships_Buttons_Pressed
Position 259 - 460

**Comment by FootyMD** [comment]
Are those entity files? or directly in the svipul research entity?

**Comment by kabivel** [comment]
[Svipul.zip](https://github.com/JCharante/Sins-of-a-New-Eden-Empire/files/861193/Svipul.zip)
Svipul Fix 
Type: Update
Change to manifest: No
Folders affected: Window - Textures
