### ISSUE TITLE
Bhaalgorn has no unlock research

### ISSUE THREAD

**Issue by FootyMD** [JCharante/Sins-of-a-New-Eden-Empire#6]

**Comment by kabivel** [comment]
Bhaalgorn dont have research, the access is given as soon you get an artifact.

	NumResearchPrerequisites 1
	ResearchPrerequisite
		Subject "RESEARCHSUBJECT_ARTIFACT_WORMHOLETRAVEL"
		Level 1
	RequiredFactionNameID ""
	RequiredCompletedResearchSubjects 0

**Comment by FootyMD** [comment]
what entities are the artifacts under?

**Comment by kabivel** [comment]
GalaxyScenarioDef
