### ISSUE TITLE
Re add the colonize ability to rorq

### ISSUE THREAD

**Issue by FootyMD** [JCharante/Sins-of-a-New-Eden-Empire#7]
I think this may be part of the problem with the ai, would like to test

**Comment by kabivel** [comment]
What ability should be removed ?
ability:0 "AbilityRorqualExtractor"
ability:1 "AbilityPLASMASmartbomb"
ability:2 "AbilityRorqualShieldBooster"
ability:3 "AbilityRorqualPanic"

My sugestion is ability:1

**Comment by FootyMD** [comment]
agreed

**Comment by kabivel** [comment]
Fixed
