### ISSUE TITLE
All t2 upgrades require 4 lvls of the t1 varions

### ISSUE THREAD

**Issue by FootyMD** [JCharante/Sins-of-a-New-Eden-Empire#8]
Basically just need to edit levels in the research for each t2

**Comment by kabivel** [comment]
This change can only be done after we got the rebalance costs done

**Comment by JCharante** [comment]
Is having 5 lvls a possibility?

**Comment by FootyMD** [comment]
We can temp edit them to only req 1 level

**Comment by kabivel** [comment]
Rolled back version. Fixed
